(ns listingops.publish
  "Generate `listingops.edge.snapshot` — the admission-cleared snapshot
  the buyer Worker serves.

  Run from the JVM so the snapshot is produced by the SAME
  `listingops.surface` code the actor's tests exercise. The Worker then
  contains data, not admission logic.

  `clojure -M:dev:snapshot`"
  (:require [clojure.java.io :as io]
            [clojure.string :as str]
            [listingops.store :as store]
            [listingops.surface :as surface])
  (:import (java.time Instant)))

(def ^:private out "src/listingops/edge/snapshot.cljs")

(defn -main [& args]
  (let [now (or (first args) "2026-06-01T00:00:00Z")
        generated-at (str (Instant/now))
        st (store/seed-db)
        snap (surface/publish st now generated-at)]
    (io/make-parents out)
    (spit out
          (str ";; GENERATED by `clojure -M:dev:snapshot` — do not edit.\n"
               ";; The admission-cleared buyer surface, frozen. Built from\n"
               ";; listingops.surface/publish, so a refused listing is absent\n"
               ";; from this data rather than filtered out at render time.\n"
               "(ns listingops.edge.snapshot)\n\n"
               "(def data\n  "
               (str/replace (pr-str snap) #"\n" " ")
               ")\n"))
    (println "wrote" out)
    (println "  listings :" (:snapshot/listing-count snap))
    (println "  products :" (count (:snapshot/sitemap snap)))
    (println "  sellers  :" (count (:snapshot/sellers snap)))
    (println "  as-of    :" (:snapshot/as-of snap))))
